{
            "all_tpks": [
                {
                    "exclusive_countries": [],
                    "machine_name": "2danimation_softwarebundle_bt1_reallusion",
                    "gamekey": "2AZm2qDRvVUeqbKY",
                    "custom_instructions_html": "<div class=\"instructions_html overgrowthspf_instruct\" style=\"text-align: center;\">\r\n\t<center>\r\n\t\t<p style=\"font-size: 15px\">\r\n\t\t\t <a href=\"https://support.humblebundle.com/hc/en-us/articles/360038790114\" target=\"_blank\">Redemption Instructions</a>.\r\n\t\t</p>\r\n\t</center>\r\n</div>",
                    "disallowed_countries": [],
                    "show_custom_instructions_in_user_libraries": false,
                    "key_type": "generic",
                    "visible": true,
                    "sold_out": false,
                    "display_separately": true,
                    "direct_redeem": false,
                    "key_type_human_name": "other",
                    "keyindex": 0,
                    "human_name": "2D Animation $1 Tier",
                    "auto_expand": true,
                    "is_expired": false,
                    "class": "genericbutton",
                    "num_days_until_expired": -1
                },
                {
                    "exclusive_countries": [],
                    "machine_name": "2danimation_soft_bta_reallusion",
                    "gamekey": "2AZm2qDRvVUeqbKY",
                    "custom_instructions_html": "<div class=\"instructions_html overgrowthspf_instruct\" style=\"text-align: center;\">\r\n\t<center>\r\n\t\t<p style=\"font-size: 15px\">\r\n\t\t\t <a href=\"https://support.humblebundle.com/hc/en-us/articles/360038790114\" target=\"_blank\">Redemption Instructions</a>.\r\n\t\t</p>\r\n\t</center>\r\n</div>",
                    "disallowed_countries": [],
                    "show_custom_instructions_in_user_libraries": false,
                    "key_type": "generic",
                    "visible": true,
                    "sold_out": false,
                    "display_separately": true,
                    "direct_redeem": false,
                    "key_type_human_name": "other",
                    "keyindex": 0,
                    "human_name": "2D Animation BTA Tier",
                    "auto_expand": true,
                    "is_expired": false,
                    "class": "genericbutton",
                    "num_days_until_expired": -1
                },
                {
                    "exclusive_countries": [],
                    "machine_name": "2danimation_soft_bt25_reallusion",
                    "gamekey": "2AZm2qDRvVUeqbKY",
                    "custom_instructions_html": "<div class=\"instructions_html overgrowthspf_instruct\" style=\"text-align: center;\">\r\n\t<center>\r\n\t\t<p style=\"font-size: 15px\">\r\n\t\t\t <a href=\"https://support.humblebundle.com/hc/en-us/articles/360038790114\" target=\"_blank\">Redemption Instructions</a>.\r\n\t\t</p>\r\n\t</center>\r\n</div>",
                    "disallowed_countries": [],
                    "show_custom_instructions_in_user_libraries": false,
                    "key_type": "generic",
                    "visible": true,
                    "sold_out": false,
                    "display_separately": true,
                    "direct_redeem": false,
                    "key_type_human_name": "other",
                    "keyindex": 0,
                    "human_name": "2D Animation $25 Tier",
                    "auto_expand": true,
                    "is_expired": false,
                    "class": "genericbutton",
                    "num_days_until_expired": -1
                }
            ]
        }