{
                    "exclusive_countries": [],
                    "machine_name": "2danimation_softwarebundle_bt1_reallusion",
                    "gamekey": "2AZm2qDRvVUeqbKY",
                    "custom_instructions_html": "<div class=\"instructions_html overgrowthspf_instruct\" style=\"text-align: center;\">\r\n\t<center>\r\n\t\t<p style=\"font-size: 15px\">\r\n\t\t\t <a href=\"https://support.humblebundle.com/hc/en-us/articles/360038790114\" target=\"_blank\">Redemption Instructions</a>.\r\n\t\t</p>\r\n\t</center>\r\n</div>",
                    "disallowed_countries": [],
                    "show_custom_instructions_in_user_libraries": false,
                    "key_type": "generic",
                    "visible": true,
                    "sold_out": false,
                    "display_separately": true,
                    "direct_redeem": false,
                    "key_type_human_name": "other",
                    "keyindex": 0,
                    "human_name": "2D Animation $1 Tier",
                    "auto_expand": true,
                    "is_expired": false,
                    "class": "genericbutton",
                    "num_days_until_expired": -1
                }
{
    "machine_name": "clannad_bundle_steam",
    "gamekey": "2cut2AGkahN7WqBK",
    "exclusive_countries": [],
    "num_days_until_expired": -1,
    "disallowed_countries": [],
    "show_custom_instructions_in_user_libraries": false,
    "key_type": "steam",
    "visible": true,
    "sold_out": false,
    "instructions_html": "<a href='https://support.humblebundle.com/hc/articles/204008710-How-To-Redeem-Steam-Keys' target='_blank'>Steam Instructions</a>",
    "display_separately": false,
    "direct_redeem": false,
    "key_type_human_name": "Steam",
    "steam_app_id": null,
    "human_name": "CLANNAD",
    "preinstruction_text": "Copy this key into the Steam client, or click Redeem to redeem in-browser.",
    "auto_expand": true,
    "is_expired": false,
    "class": "steambutton",
    "keyindex": 0,
    "disclaimer": "Steam will not provide extra giftable copies of games you already own."
}
{
    "machine_name": "sunrider_liberationday_captainsedition_bundle_steam",
    "gamekey": "2cut2AGkahN7WqBK",
    "exclusive_countries": [],
    "num_days_until_expired": -1,
    "disallowed_countries": [],
    "show_custom_instructions_in_user_libraries": false,
    "key_type": "steam",
    "visible": true,
    "sold_out": false,
    "instructions_html": "<a href='https://support.humblebundle.com/hc/articles/204008710-How-To-Redeem-Steam-Keys' target='_blank'>Steam Instructions</a>",
    "display_separately": false,
    "direct_redeem": false,
    "key_type_human_name": "Steam",
    "steam_app_id": 438130,
    "human_name": "Sunrider: Liberation Day - Captain's Edition",
    "preinstruction_text": "Copy this key into the Steam client, or click Redeem to redeem in-browser.",
    "auto_expand": true,
    "is_expired": false,
    "class": "steambutton",
    "keyindex": 0,
    "disclaimer": "Steam will not provide extra giftable copies of games you already own."
},
{
    "machine_name": "sunrider_liberationday_themesong_bundle_steam",
    "gamekey": "2cut2AGkahN7WqBK",
    "exclusive_countries": [],
    "num_days_until_expired": -1,
    "disallowed_countries": [],
    "show_custom_instructions_in_user_libraries": false,
    "key_type": "steam",
    "visible": true,
    "sold_out": false,
    "instructions_html": "<a href='https://support.humblebundle.com/hc/articles/204008710-How-To-Redeem-Steam-Keys' target='_blank'>Steam Instructions</a>",
    "display_separately": false,
    "direct_redeem": false,
    "key_type_human_name": "Steam",
    "steam_app_id": null,
    "human_name": "Sunrider: Liberation Day - Theme Song",
    "preinstruction_text": "Copy this key into the Steam client, or click Redeem to redeem in-browser.",
    "auto_expand": true,
    "is_expired": false,
    "class": "steambutton",
    "keyindex": 0,
    "disclaimer": "Steam will not provide extra giftable copies of games you already own."
},
{
    "machine_name": "sunrideracademy_bundle_steam",
    "gamekey": "2cut2AGkahN7WqBK",
    "exclusive_countries": [],
    "num_days_until_expired": -1,
    "disallowed_countries": [],
    "show_custom_instructions_in_user_libraries": false,
    "key_type": "steam",
    "visible": true,
    "sold_out": false,
    "instructions_html": "<a href='https://support.humblebundle.com/hc/articles/204008710-How-To-Redeem-Steam-Keys' target='_blank'>Steam Instructions</a>",
    "display_separately": false,
    "direct_redeem": false,
    "key_type_human_name": "Steam",
    "steam_app_id": 340730,
    "human_name": "Sunrider Academy",
    "preinstruction_text": "Copy this key into the Steam client, or click Redeem to redeem in-browser.",
    "auto_expand": true,
    "is_expired": false,
    "class": "steambutton",
    "keyindex": 0,
    "disclaimer": "Steam will not provide extra giftable copies of games you already own."
},
{
    "machine_name": "gsenjounomaou_thedevilongstring_bundle_steam",
    "gamekey": "2cut2AGkahN7WqBK",
    "exclusive_countries": [],
    "num_days_until_expired": -1,
    "disallowed_countries": [],
    "show_custom_instructions_in_user_libraries": false,
    "key_type": "steam",
    "visible": true,
    "sold_out": false,
    "instructions_html": "<a href='https://support.humblebundle.com/hc/articles/204008710-How-To-Redeem-Steam-Keys' target='_blank'>Steam Instructions</a>",
    "display_separately": false,
    "direct_redeem": false,
    "key_type_human_name": "Steam",
    "steam_app_id": null,
    "human_name": "G-senjou no Maou - The Devil on G-String Voiced Edition",
    "preinstruction_text": "Copy this key into the Steam client, or click Redeem to redeem in-browser.",
    "auto_expand": true,
    "is_expired": false,
    "class": "steambutton",
    "keyindex": 0,
    "disclaimer": "Steam will not provide extra giftable copies of games you already own."
},
{
    "machine_name": "genitaljousting_bundle_steam",
    "gamekey": "2cut2AGkahN7WqBK",
    "exclusive_countries": [],
    "num_days_until_expired": -1,
    "disallowed_countries": [],
    "show_custom_instructions_in_user_libraries": false,
    "key_type": "steam",
    "visible": true,
    "sold_out": false,
    "instructions_html": "<a href='https://support.humblebundle.com/hc/articles/204008710-How-To-Redeem-Steam-Keys' target='_blank'>Steam Instructions</a>",
    "display_separately": false,
    "direct_redeem": false,
    "key_type_human_name": "Steam",
    "steam_app_id": null,
    "human_name": "Genital Jousting",
    "preinstruction_text": "Copy this key into the Steam client, or click Redeem to redeem in-browser.",
    "auto_expand": true,
    "is_expired": false,
    "class": "steambutton",
    "keyindex": 0,
    "disclaimer": "Steam will not provide extra giftable copies of games you already own."
},
{
    "machine_name": "purrfectdate_bundle_steam",
    "gamekey": "2cut2AGkahN7WqBK",
    "exclusive_countries": [],
    "num_days_until_expired": -1,
    "disallowed_countries": [],
    "show_custom_instructions_in_user_libraries": false,
    "key_type": "steam",
    "visible": true,
    "sold_out": false,
    "instructions_html": "<a href='https://support.humblebundle.com/hc/articles/204008710-How-To-Redeem-Steam-Keys' target='_blank'>Steam Instructions</a>",
    "display_separately": false,
    "direct_redeem": false,
    "key_type_human_name": "Steam",
    "steam_app_id": null,
    "human_name": "Purrfect Date - Visual Novel/Dating Simulator",
    "preinstruction_text": "Copy this key into the Steam client, or click Redeem to redeem in-browser.",
    "auto_expand": true,
    "is_expired": false,
    "class": "steambutton",
    "keyindex": 0,
    "disclaimer": "Steam will not provide extra giftable copies of games you already own."
},
{
    "machine_name": "ladykillerinabind_bundle_steam",
    "gamekey": "2cut2AGkahN7WqBK",
    "exclusive_countries": [],
    "num_days_until_expired": -1,
    "disallowed_countries": [],
    "show_custom_instructions_in_user_libraries": false,
    "key_type": "steam",
    "visible": true,
    "sold_out": false,
    "instructions_html": "<a href='https://support.humblebundle.com/hc/articles/204008710-How-To-Redeem-Steam-Keys' target='_blank'>Steam Instructions</a>",
    "display_separately": false,
    "direct_redeem": false,
    "key_type_human_name": "Steam",
    "steam_app_id": null,
    "human_name": "Ladykiller in a Bind",
    "preinstruction_text": "Copy this key into the Steam client, or click Redeem to redeem in-browser.",
    "auto_expand": true,
    "is_expired": false,
    "class": "steambutton",
    "keyindex": 0,
    "disclaimer": "Steam will not provide extra giftable copies of games you already own."
},
{
    "machine_name": "justdeserts_bundle_steam",
    "gamekey": "2cut2AGkahN7WqBK",
    "exclusive_countries": [],
    "num_days_until_expired": -1,
    "disallowed_countries": [],
    "show_custom_instructions_in_user_libraries": false,
    "key_type": "steam",
    "visible": true,
    "sold_out": false,
    "instructions_html": "<a href='https://support.humblebundle.com/hc/articles/204008710-How-To-Redeem-Steam-Keys' target='_blank'>Steam Instructions</a>",
    "display_separately": false,
    "direct_redeem": false,
    "key_type_human_name": "Steam",
    "steam_app_id": 488660,
    "human_name": "Just Deserts",
    "preinstruction_text": "Copy this key into the Steam client, or click Redeem to redeem in-browser.",
    "auto_expand": false,
    "is_expired": false,
    "class": "steambutton",
    "keyindex": 0,
    "disclaimer": "Steam will not provide extra giftable copies of games you already own."
},
{
    "machine_name": "highwayblossoms_bundle_steam",
    "gamekey": "2cut2AGkahN7WqBK",
    "exclusive_countries": [],
    "num_days_until_expired": -1,
    "disallowed_countries": [],
    "show_custom_instructions_in_user_libraries": false,
    "key_type": "steam",
    "visible": true,
    "sold_out": false,
    "instructions_html": "<a href='https://support.humblebundle.com/hc/articles/204008710-How-To-Redeem-Steam-Keys' target='_blank'>Steam Instructions</a>",
    "display_separately": false,
    "direct_redeem": false,
    "key_type_human_name": "Steam",
    "steam_app_id": 451760,
    "human_name": "Highway Blossoms",
    "preinstruction_text": "Copy this key into the Steam client, or click Redeem to redeem in-browser.",
    "auto_expand": true,
    "is_expired": false,
    "class": "steambutton",
    "keyindex": 0,
    "disclaimer": "Steam will not provide extra giftable copies of games you already own."
},
{
    "machine_name": "creatureromances_kokonoekokoro_bundle_steam",
    "gamekey": "2cut2AGkahN7WqBK",
    "exclusive_countries": [],
    "num_days_until_expired": -1,
    "disallowed_countries": [],
    "show_custom_instructions_in_user_libraries": false,
    "key_type": "steam",
    "visible": true,
    "sold_out": false,
    "instructions_html": "<a href='https://support.humblebundle.com/hc/articles/204008710-How-To-Redeem-Steam-Keys' target='_blank'>Steam Instructions</a>",
    "display_separately": false,
    "direct_redeem": false,
    "key_type_human_name": "Steam",
    "steam_app_id": null,
    "human_name": "Creature Romances: Kokonoe Kokoro",
    "preinstruction_text": "Copy this key into the Steam client, or click Redeem to redeem in-browser.",
    "auto_expand": true,
    "is_expired": false,
    "class": "steambutton",
    "keyindex": 0,
    "disclaimer": "Steam will not provide extra giftable copies of games you already own."
},
{
    "exclusive_countries": [],
    "machine_name": "2danimation_soft_bt25_reallusion",
    "gamekey": "2AZm2qDRvVUeqbKY",
    "custom_instructions_html": "<div class=\"instructions_html overgrowthspf_instruct\" style=\"text-align: center;\">\r\n\t<center>\r\n\t\t<p style=\"font-size: 15px\">\r\n\t\t\t <a href=\"https://support.humblebundle.com/hc/en-us/articles/360038790114\" target=\"_blank\">Redemption Instructions</a>.\r\n\t\t</p>\r\n\t</center>\r\n</div>",
    "disallowed_countries": [],
    "show_custom_instructions_in_user_libraries": false,
    "key_type": "generic",
    "visible": true,
    "sold_out": false,
    "display_separately": true,
    "direct_redeem": false,
    "key_type_human_name": "other",
    "keyindex": 0,
    "human_name": "2D Animation $25 Tier",
    "auto_expand": true,
    "is_expired": false,
    "class": "genericbutton",
    "num_days_until_expired": -1
}
{
    "exclusive_countries": [],
    "machine_name": "2danimation_soft_bta_reallusion",
    "gamekey": "2AZm2qDRvVUeqbKY",
    "custom_instructions_html": "<div class=\"instructions_html overgrowthspf_instruct\" style=\"text-align: center;\">\r\n\t<center>\r\n\t\t<p style=\"font-size: 15px\">\r\n\t\t\t <a href=\"https://support.humblebundle.com/hc/en-us/articles/360038790114\" target=\"_blank\">Redemption Instructions</a>.\r\n\t\t</p>\r\n\t</center>\r\n</div>",
    "disallowed_countries": [],
    "show_custom_instructions_in_user_libraries": false,
    "key_type": "generic",
    "visible": true,
    "sold_out": false,
    "display_separately": true,
    "direct_redeem": false,
    "key_type_human_name": "other",
    "keyindex": 0,
    "human_name": "2D Animation BTA Tier",
    "auto_expand": true,
    "is_expired": false,
    "class": "genericbutton",
    "num_days_until_expired": -1
},
